###########################################
# Expect script to give password to scp   #
# Author : Arnaud Schoofs                 #
###########################################

#!/usr/bin/expect -f

set password [lrange $argv 0 0]
set dest [lrange $argv 1 1]
set filename [lrange $argv 2 2]
set timeout -1
spawn scp -rp $filename $dest
match_max 100000
expect "*?assword:*"
send -- "$password\r"
send -- "\r"
expect eof
